language: node_js
node_js:
  - '10'
cache:
  npm: true
  directories:
    - ~/.cache
addons:
  chrome: stable
  apt:
    packages:
      - libgconf-2-4 #Needed to run Cypress if not already installed in dist
install:
    - npm ci

# Integration Test stage
integrationTests: &integrationTest
  if: env(RUN_CYPRESS) = true
  script:  "$(npm bin)/cypress run --record --key $cypressDashboard --parallel --group crds-media-parallel --config-file ./cypress/config/int_crossroads.json"

jobs:
  include:
  # run tests in parallel by including several jobs with same "stage" name
    - stage: Integraion Tests
      <<: *integrationTest
    - stage: Integraion Tests
      <<: *integrationTest
    - stage: Integraion Tests
      <<: *integrationTest

notifications:
  slack:
    rooms:
      - crdschurch:iZZLQf36DkUtiv0SqLhlOklj
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} by %{author} %{result} in %{elapsed_time}"
    on_success: always
    on_failure: always
    on_pull_requests: false