title: Crossroads Media
email: info@crossroads.net
description: No matter what your beliefs, you are welcome here.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.crossroads.net/media" # the base hostname & protocol for your site, e.g. http://example.com
image: "//crds-cms-uploads.imgix.net/content/images/cr-social-sharing-still-bg.jpg?auto=format&w=1200&h=630&fit=crop"

# disable_hubspot: true
permalink: /:title/

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-contentful

# The following items will not be processed, by default.
exclude:
  - .github/
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - lib
  - node_modules
  - package-lock.json
  - package.json
  - README.md
  - spec
  - tmp
  - vendor
  - buildlog.txt
  - gulpfile.js

include:
  - _redirects
  - _headers

collections_dir: collections

collections:
  albums:
    output: false
  articles:
    output: true
    permalink: /:collection/:title
    filename: "{{ published_at | date: '%Y-%m-%d' }}-{{ slug }}"
  categories:
    output: true
    permalink: /topics/:title
  collections:
    output: true
    permalink: /collections/:title
  authors:
    output: true
    permalink: /:collection/:title
  podcasts:
    output: true
    permalink: /:collection/:title
  episodes:
    output: true
    permalink: /podcasts/(:podcast/:slug)/:title
  videos:
    output: true
    permalink: /:collection/:title
  series:
    output: true
    permalink: /:collection/:title
  messages:
    output: true
    permalink: /series/(:series/:slug)/:title
  tags:
    output: false
  featured_media:
    output: false
  discussions:
    output: false
  sign_offs:
    output: false
  perspectives:
    output: true
    permalink: /:collection/:title
  perspective_sets:
    output: true
    permalink: /perspectives/sets/:title
  promos:
    output: false
  content_blocks:
    output: false
  system_pages:
    output: true

contentful:
  config:
    sites: distribution_channels 
  collection:
  podcast:
  album:
    map:
      date: published_at
  article:
    map:
      date: published_at
  discussion:
    map:
      date: published_at
  episode:
    map:
      date: published_at
  featured_media:
    query: fields.site=media
    map:
      page_path: path
  message:
    map:
      date: published_at
    belongs_to:
      series: videos
  series:
    map:
      date: published_at
  video:
    map:
      date: published_at
  perspective:
    map:
      date: published_at
  perspective_set:
    map:
      date: published_at
  content_block:
    query: fields.category=media
    map:
      description: content
  exclude:
    - location
    - migrations
    - page
    - redirect
    - song

defaults:
  - scope:
      path: ""
    values:
      js_manifest: application_deferred
  - scope:
      path: ""
      type: articles
    values:
      layout: article
  - scope:
      path: ""
      type: collections
    values:
      layout: collection
  - scope:
      path: ""
      type: categories
    values:
      layout: topic
  - scope:
      path: ""
      type: collections
    values:
      layout: collection
  - scope:
      path: ""
      type: authors
    values:
      layout: author
  - scope:
      path: ""
      type: podcasts
    values:
      layout: podcast
  - scope:
      path: ""
      type: episodes
    values:
      layout: episode
  - scope:
      path: ""
      type: videos
    values:
      layout: video
  - scope:
      path: ""
      type: series
    values:
      layout: series
  - scope:
      path: ""
      type: messages
    values:
      layout: message
  - scope:
      path: ""
      type: perspectives
    values:
      layout: perspective
  - scope:
      path: ""
      type: perspective_sets
    values:
      layout: perspective_set

imgix_params:
  overlay_50: "blend64=MTUxNTE1&balph=50&bm=normal"
  placeholder: "auto=format,compress&w=10"
  placeholder_card: "auto=format,compress&w=12&h=9&fit=crop"
  placeholder_square: "auto=format,compress&w=10&h=10&fit=crop"
  placeholder_sixteen_nine: "auto=format,compress&w=16&h=9&fit=crop"
  meta_image: "auto=format,compress&w=1200&h=630&fit=crop"

image_sizes:
  media_object: "(min-width: 768px) 140px, (min-width: 0px) 100px"
  cards_6x: "(min-width: 992px) 165px, (min-width: 0px) 50vw"
  cards_4x: "(min-width: 992px) 212.5px, (min-width: 768px) 345px, (min-width: 0px) 100vw"
  cards_3x: "(min-width: 992px) 390px, (min-width: 0px) 100vw"
  cards_3x_centered_carousel: "(min-width: 1200px) 232.5px, (min-width: 992px) 191px, (min-width: 768px) 146px, (min-width: 0px) 270px"
  cards_2x: "(min-width: 768px) 345px, (min-width: 0px) 100vw"
  podcast_thumb: "(min-width: 768px) 330px, (min-width: 480px) 200px, (min-width: 0px) 100vw"
  episode_thumb: "(min-width: 768px) 120px, (min-width: 0px) 80px"
  avatar: "80px"
  full_width: "100vw"
  half_width: "50vw"
  one_hundred: "100%"
  topic_feature_sub: "(min-width: 992px) 370px, (min-width: 0px) 100px"

typekit_url: https://use.typekit.net/gir0nnu.css
typekit_scss: _assets/stylesheets/_fonts.scss
