# default build settings for int, preview deploys etc
[build]
  command = "bin/build-command.sh"
  functions = "_functions"

[context.branch-deploy.environment]
  CRDS_PEOPLE_DOMAIN = "people-int.crossroads.net"
  CRDS_MAP_DOMAIN = "connect-int.crossroads.net"
  CRDS_ANGULAR_ENDPOINT = "development--crds-angular.netlify.app"
  CRDS_SIGNIN_ENDPOINT = "development.signin.crossroads.net"
  CRDS_SERVE_ENDPOINT = "development.serve.crossroads.net"
  CRDS_PROFILE_ENDPOINT = "development.profile.crossroads.net"
  CRDS_EVENT_CHECKIN_ENDPOINT = "development.event-checkin.crossroads.net"
  CRDS_FOCUS_MISSION = "https://crds.sandbox.focusmissions.com/"
  CRDS_COMPONENTS_ENDPOINT = "components-int.crossroads.net"

[context.deploy-preview.environment]
  CRDS_PEOPLE_DOMAIN = "people-int.crossroads.net"
  CRDS_MAP_DOMAIN = "connect-int.crossroads.net"
  CRDS_ANGULAR_ENDPOINT = "development--crds-angular.netlify.app"
  CRDS_SIGNIN_ENDPOINT = "development.signin.crossroads.net"
  CRDS_SERVE_ENDPOINT = "development.serve.crossroads.net"
  CRDS_PROFILE_ENDPOINT = "development.profile.crossroads.net"
  CRDS_EVENT_CHECKIN_ENDPOINT = "development.event-checkin.crossroads.net"
  CRDS_FOCUS_MISSION = "https://crds.sandbox.focusmissions.com/"
  CRDS_COMPONENTS_ENDPOINT = "components-int.crossroads.net"

[context.development.environment]
  CRDS_PEOPLE_DOMAIN = "people-int.crossroads.net"
  CRDS_MAP_DOMAIN = "connect-int.crossroads.net"
  CRDS_ANGULAR_ENDPOINT = "development--crds-angular.netlify.app"
  CRDS_SIGNIN_ENDPOINT = "development.signin.crossroads.net"
  CRDS_SERVE_ENDPOINT = "development.serve.crossroads.net"
  CRDS_PROFILE_ENDPOINT = "development.profile.crossroads.net"
  CRDS_EVENT_CHECKIN_ENDPOINT = "development.event-checkin.crossroads.net"
  CRDS_FOCUS_MISSION = "https://crds.sandbox.focusmissions.com/"
  CRDS_COMPONENTS_ENDPOINT = "components-int.crossroads.net"

[context.runway.environment]
  CRDS_PEOPLE_DOMAIN = "people-int.crossroads.net"
  CRDS_MAP_DOMAIN = "connect-int.crossroads.net"
  CRDS_ANGULAR_ENDPOINT = "development--crds-angular.netlify.app"
  CRDS_SIGNIN_ENDPOINT = "development.signin.crossroads.net"
  CRDS_SERVE_ENDPOINT = "development.serve.crossroads.net"
  CRDS_PROFILE_ENDPOINT = "development.profile.crossroads.net"
  CRDS_EVENT_CHECKIN_ENDPOINT = "development.event-checkin.crossroads.net"
  CRDS_FOCUS_MISSION = "https://crds.sandbox.focusmissions.com/"
  CRDS_COMPONENTS_ENDPOINT = "components-int.crossroads.net"

[context.release.environment]
  CRDS_PEOPLE_DOMAIN = "people-int.crossroads.net"
  CRDS_MAP_DOMAIN = "connect-int.crossroads.net"
  CRDS_ANGULAR_ENDPOINT = "release--crds-angular.netlify.app"
  CRDS_SIGNIN_ENDPOINT = "release.signin.crossroads.net"
  CRDS_SERVE_ENDPOINT = "release.serve.crossroads.net"
  CRDS_PROFILE_ENDPOINT = "release.profile.crossroads.net"
  CRDS_EVENT_CHECKIN_ENDPOINT = "release.event-checkin.crossroads.net"
  CRDS_FOCUS_MISSION = "https://crds.sandbox.focusmissions.com/"
  CRDS_COMPONENTS_ENDPOINT = "components-demo.crossroads.net"

[context.master.environment]
  CRDS_PEOPLE_DOMAIN = "people.crossroads.net"
  CRDS_MAP_DOMAIN = "connect.crossroads.net"
  CRDS_ANGULAR_ENDPOINT = "crds-angular.crossroads.net"
  CRDS_SIGNIN_ENDPOINT = "signin.crossroads.net"
  CRDS_SERVE_ENDPOINT = "serve.crossroads.net"
  CRDS_PROFILE_ENDPOINT = "profile.crossroads.net"
  CRDS_EVENT_CHECKIN_ENDPOINT = "event-checkin.crossroads.net"
  CRDS_FOCUS_MISSION = "https://crds.focusmissions.com/"
  CRDS_COMPONENTS_ENDPOINT = "components.crossroads.net"

[context.rebrand.environment]
  CRDS_COMPONENTS_ENDPOINT = "deploy-preview-480--crds-components-int.netlify.app"
