[build]
  command = "bin/build-command.sh"

[context.development.environment]
  BASEURL="/media"
  CRDS_COMPONENTS_ENDPOINT="components-int.crossroads.net"
  CRDS_COMPONENTS_ROOT_URL="https://int.crossroads.net"

[context.release.environment]
  BASEURL="/media"
  CRDS_COMPONENTS_ENDPOINT="components-demo.crossroads.net"
  CRDS_COMPONENTS_ROOT_URL="https://demo.crossroads.net"

[context.master.environment]
  BASEURL="/media"
  CRDS_COMPONENTS_ENDPOINT="components.crossroads.net"
  CRDS_COMPONENTS_ROOT_URL="https://www.crossroads.net"

[context.deploy-preview.environment]
  BASEURL="/"
  CRDS_COMPONENTS_ENDPOINT="components-int.crossroads.net"
  CRDS_COMPONENTS_ROOT_URL="https://int.crossroads.net"
