title: Crossroads
email: info@crossroads.net
description: No matter what your beliefs, you are welcome here.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.crossroads.net" # the base hostname & protocol for your site, e.g. http://example.com
image: "//crds-media.imgix.net/7EFusaW9y0WFSxO9KCdumH/2edc127ce50430b3894692f7075122fb/spiritual-outfitters.jpg"

# Build settings
# disable_hubspot: true
permalink: pretty

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-contentful

# The following items will not be processed, by default.
exclude:
  - .github/
  - bin
  - cypress.json
  - Guardfile
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - lib
  - package.json
  - package-lock.json
  - _migrations
  - netlify.toml
  - node_modules
  - Rakefile
  - README.md
  - spec
  - tmp
  - vendor
  - buildlog.txt
  - collections

include:
  - .aws
  - _redirects
  - _headers
  - _pages

collections_dir: collections

collections:
  albums:
    output: false
  articles:
    output: false
  authors:
    output: false
  categories:
    output: false
    permalink: /topics/:title
  content_blocks:
    output: false
  episodes:
    output: false
    permalink: /podcasts/(:podcast/:slug)/:title
  featured_media:
    output: false
  features:
    output: false
  locations:
    output: true
    permalink: /:slug
  messages:
    filename: "{{ published_at | date: '%Y-%m-%d' }}-{{ slug }}"
    output: false
    permalink: /series/(:series/:slug)/:title
  onsite_group_categories:
    output: false
  onsite_group_meetings:
    output: false
  onsite_groups:
    output: true
    permalink: /groups/(:category/:slug)/:slug
  pages:
    filename: "{{ permalink }} index"
    output: true
    permalink: /:permalink/index.html
  perspectives:
    output: false
    permalink: /:collection/:title
  podcasts:
    output: true
  promos:
    filename: "{{ published_at | date: '%Y-%m-%d-%H-%M-%S' }}-{{ title | slugify }}-{{ slug }}"
    output: false
  series:
    filename: "{{ published_at | date: '%Y-%m-%d' }}-{{ slug }}"
    output: false
    has_many:
      - videos
    permalink: /:collection/:title
  songs:
    output: false
  system_pages:
    output: false
  tags:
    output: false
  topics:
    output: false
  trips:
    output: true
    permalink: /reachout/go/:country_slug/:slug
  videos:
    output: false

contentful:
  config:
    sites: distribution_channels
  article:
    map:
      date: published_at
  category:
  content_block:
    map:
      content_block: content
  episode:
    map:
      date: published_at
  featured_media:
    query: fields.site=net
    map:
      page_path: path
  message:
    limit: 6
    order: "published_at desc"
    map:
      date: published_at
  page:
  podcast:
  query:
  series:
    limit: 10
    order: "published_at desc"
    map:
      date: published_at
  video:
  exclude:
    - collections
    - location
    - migration
    - migrations
    - page
    - redirect
    - sign_off
    - song

defaults:
  - scope:
      path: ""
    values:
      js_manifest: application_deferred
  - scope:
      path: ""
      type: articles
    values:
      layout: article
  - scope:
      path: ""
      type: authors
    values:
      layout: author
  - scope:
      path: ""
      type: categories
    values:
      layout: topic
  - scope:
      path: ""
      type: collections
    values:
      layout: collection
  - scope:
      path: ""
      type: episodes
    values:
      layout: episode
  - scope:
      path: ""
      type: "locations"
    values:
      layout: location
  - scope:
      path: ""
      type: messages
    values:
      layout: message
  - scope:
      path: ""
      type: "onsite_groups"
    values:
      layout: onsite-group-detail
      snail_trail: connect
  - scope:
      path: ""
      type: perspective_sets
    values:
      layout: perspective_set
  - scope:
      path: ""
      type: perspectives
    values:
      layout: perspective
  - scope:
      path: ""
      type: podcasts
    values:
      layout: podcast
  - scope:
      path: ""
      type: series
    values:
      layout: series
  - scope:
      path: ""
      type: "trips"
    values:
      layout: trip
  - scope:
      path: ""
      type: videos
    values:
      layout: video

imgix_params:
  meta_image: "auto=format,compress&w=1200&h=630&fit=crop"
  overlay_50: "blend64=MTUxNTE1&balph=50&bm=normal"
  placeholder: "auto=format,compress&w=10"
  placeholder_card: "auto=format,compress&w=12&h=9&fit=crop"
  placeholder_sixteen_nine: "auto=format,compress&w=16&h=9&fit=crop"
  placeholder_square: "auto=format,compress&w=10&h=10&fit=crop"
  thin_hero: "auto=format,compress&fit=crop&crop=faces&w=3.125h=1"

image_sizes:
  avatar: "80px"
  cards_2x: "(min-width: 768px) 345px, (min-width: 0px) 100vw"
  cards_3x: "(min-width: 992px) 390px, (min-width: 0px) 100vw"
  cards_3x_centered_carousel: "(min-width: 1200px) 232.5px, (min-width: 992px) 191px, (min-width: 768px) 146px, (min-width: 0px) 270px"
  cards_4x: "(min-width: 992px) 212.5px, (min-width: 768px) 345px, (min-width: 0px) 100vw"
  cards_6x: "(min-width: 992px) 165px, (min-width: 0px) 50vw"
  episode_thumb: "(min-width: 768px) 120px, (min-width: 0px) 80px"
  full_width: "100vw"
  half_width: "50vw"
  media_object: "(min-width: 768px) 140px, (min-width: 0px) 100px"
  one_fourth: "(min-width: 992px) 25vw, (min-width: 0px) 100vw"
  one_hundred: "100%"
  podcast_thumb: "(min-width: 768px) 330px, (min-width: 480px) 200px, (min-width: 0px) 100vw"
  three_fourths: "(min-width: 992px) 75vw, (min-width: 0px) 100vw"
  topic_feature_sub: "(min-width: 992px) 370px, (min-width: 0px) 100px"

typekit_url: https://use.typekit.net/gir0nnu.css
typekit_scss: _assets/stylesheets/_fonts.scss
